{% set version = "2.1.1" %}

package:
  name: django_polymorphic
  version: {{ version }}

source:
  url: https://github.com/django-polymorphic/django-polymorphic/archive/v{{ version }}.tar.gz
  sha256: 85dee9e9a1ac242921e96247a9a4fe075d2b1432157233884db833893ef122d0

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - django >1.8,<2.0

test:
  imports:
    - polymorphic

about:
  home: https://github.com/chrisglass/django_polymorphic
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Seamless Polymorphic Inheritance for Django Models
  dev_url: https://github.com/django-polymorphic/django-polymorphic
  doc_url: https://django-polymorphic.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
