{% set name = "django_polymorphic" %}
{% set version = "0.9.2" %}
{% set md5 = "12eeec306ba79aa39115c0aa61353933" %}
{% set build = 0 %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    md5: {{ md5 }}

build:
    number: {{ build }}
    preserve_egg_dir: True
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - django

test:
    imports:
        - polymorphic

about:
    home: https://github.com/chrisglass/django_polymorphic
    license: BSD-3-Clause
    summary: Seamless Polymorphic Inheritance for Django Models

extra:
    recipe-maintainers:
        - kwilcox
        - ocefpaf
