{% set name = "django_polymorphic" %}
{% set version = "4.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ced3a0dec4da117e4ec49364870d04b39d941069b1c94983386c848f1acbdf8b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - django >=2.1

test:
  imports:
    - polymorphic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/chrisglass/django_polymorphic
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Seamless Polymorphic Inheritance for Django Models
  dev_url: https://github.com/django-polymorphic/django-polymorphic
  doc_url: https://django-polymorphic.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
